spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
  jpa:
    properties:
      hibernate:
        default_schema: public
  mail:
    host: smtp.gmail.com
    port: 587
    username: sigmafoodcompany@gmail.com
    password: ilnxeqwxtovawehz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
springdoc:
  api-docs:
    path: "/api-docs"
authentication:
  public-key: classpath:public.key
  private-key: classpath:private.key
  access-token-expiration-minutes: 5
  refresh-token-expiration-hours: 24
logging:
  level:
    com.sigmamales.sigmafoodserver: debug
    org:
      springframework:
        security: debug