spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
  jpa:
    properties:
      hibernate:
        default_schema: public
  mail:
    host: smtp.gmail.com
    port: 587
    username: sigmafoodcompany@gmail.com
    password: ilnxeqwxtovawehz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
springdoc:
  api-docs:
    path: "/api-docs"
application-properties:
  access-token-expiration-minutes: 5
  refresh-token-expiration-hours: 24
  activation_token_expiration_minutes: 30
  account_activation_max_attempts: 3
logging:
  level:
    com.sigmamales.sigmafoodserver: debug
    org:
      springframework:
        security: trace
        web:
          FilterChainProxy: trace
password:
  minimum-length-enabled: true
  strength-enabled: true
