spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
  jpa:
    properties:
      hibernate:
        default_schema: public
  mail:
    host: smtp.gmail.com
    port: 587
    username: sigmafoodcompany@gmail.com
    password: ilnxeqwxtovawehz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 443
  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:sigma-food.p12
    key-store: classpath:keystore.jks
    key-store-password: 1qaz@WSX
    key-alias: sigma-food
    enabled: true
application-properties:
  access-token-expiration-minutes: 5
  refresh-token-expiration-hours: 24
  activation_token_expiration_minutes: 30
  account_activation_max_attempts: 3
logging:
  level:
    com.sigmamales.sigmafoodserver: debug
password:
  minimum-length-enabled: true
  strength-enabled: true
