package com.sigmamales.sigmafoodserver.exception.common;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,
    USER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    ORDER_NOT_FOUND,
    ORDER_PRODUCT_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    USER_ALREADY_EXISTS,
    ACTIVATION_TOKEN_NOT_FOUND,
    INVALID_ACTIVATION_TOKEN,
    INVALID_PASSWORD_EXCEPTION,
    OLD_PASSWORD_NOT_MATCH,
    COULD_NOT_EXPORT_ORDERS,
    INVALID_JWT, TOKEN_JUST_CREATED, TOKEN_ALREADY_REVOKED, TOO_MANY_PRODUCTS, CONSTRAINT_VIOLATION
}
